# Generated by Django 2.2.1 on 2019-06-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_server', '0003_auto_20190516_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse_server.Warehouse'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product_Warehouse',
        ),
    ]
