# Generated by Django 2.2.1 on 2019-06-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_server', '0004_auto_20190605_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
