# Generated by Django 2.2.1 on 2019-06-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_server', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
